# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
library(DBI)
library(DT)
library(rhino)
library(RPostgres)
library(semantic.dashboard)
library(shiny.semantic)
library(shinyjs)
library(treesitter)
library(treesitter.r)
library(trisk.analysis)
library(trisk.model)
